import { pgTable, text, varchar, boolean, timestamp, jsonb, integer } from "drizzle-orm/pg-core";

export const templates = pgTable("templates", {
  id: varchar("id", { length: 24 }).primaryKey(),
  pages: jsonb("pages").$type("object[]").default([]),
  masterinput: jsonb("masterinput").$type("object[]").default([]),
  masterinputfromother: jsonb("masterinputfromother").$type("object[]").default([]),
  importedInputSections: jsonb("imported_input_sections").$type("object[]").default([]),
  pagesfromother: jsonb("pagesfromother").$type("object[]").default([]),
  inputsections: jsonb("inputsections").$type("object[]").default([]),
  dashboards: jsonb("dashboards").$type("object[]").default([]),
  name: text("name"),
  subject: varchar("subject", { length: 512 }).default("No Subject"),
  scheme: text("scheme"),
  rulebook: text("rulebook"),
  description: text("description"),
  templateId: varchar("template_id", { length: 24 }),
  userid: varchar("userid", { length: 24 }),
  date: timestamp("date", { withTimezone: true }).defaultNow(),
  tags: jsonb("tags").$type("string[]").default([]),
  favourites: jsonb("favourites").$type("string[]").default([]),
  likedby: jsonb("likedby").$type("string[]").default([]),
  adminusers: jsonb("adminusers").$type("string[]").default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  quotes: jsonb("quotes").default([]),
  currentversion: varchar("currentversion", { length: 24 }),
  publishid: varchar("publishid", { length: 24 }),
  toPublish: boolean("to_publish").default(false),
  blogdetails: jsonb("blogdetails"),
  blocks: jsonb("blocks"),
  linktohtml: text("linktohtml"),
  isDisabled: boolean("is_disabled").default(false),
  order: integer("order").default(0),
});
